name: "anorlondon"
services:
  lordOfCinder:
    image: postgres:17.2
    container_name: "gwyn"
    restart: unless-stopped
    shm_size: 64mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - gwyn_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - majula
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

  lordOfAbyss:
    image: dpage/pgadmin4:8.14.0
    container_name: "manus"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9180:80"
    volumes:
      - manus_data:/var/lib/pgadmin
    depends_on:
      lordOfCinder:
        condition: service_healthy
    networks:
      - majula
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  gravelord:
#     build:
#      context: ./n8n-build-python
#      dockerfile: Dockerfile
    image: n8n-python:1.84.3
    container_name: "nyto"
    restart: unless-stopped
    networks:
      - majula
    env_file:
      - .env
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=gwyn
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_SECURE_COOKIE=false
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=debug
      - N8N_RUNNERS_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - GENERIC_TIMEZONE=America/Havana
    ports:
      - "5678:5678"
    volumes:
      - nyto_data:/home/node/.n8n
      - ~/anorlondo/mcp_files:/home/node/mcp
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://127.0.0.1:5678/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      lordOfCinder:
        condition: service_healthy

  crimsonDragon:
    image: portainer/portainer-ce:2.21.5
    container_name: "kalameeth"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - kalameeth_data:/data
    networks:
      - majula
    ports:
      - "9443:9443"
      - "8000:8000"

networks:
  majula:
    driver: bridge
    external: true

volumes:
  gwyn_data:
    external: true
  manus_data:
  kalameeth_data:
  nyto_data:
    external: true

